In [ ]:
from sklearn import preprocessing
import numpy as np

In [ ]:
X = np.array([[0., 0., 5., 13., 9., 1.],[0., 0., 13., 15., 10., 15.],[0., 3., 15., 2., 0., 11.]])

In [ ]:
print (preprocessing.scale(X))

[[ 0.         -0.70710678 -1.38873015  0.52489066  0.59299945 -1.35873244]
 [ 0.         -0.70710678  0.46291005  0.87481777  0.81537425  1.01904933]
 [ 0.          1.41421356  0.9258201  -1.39970842 -1.4083737   0.33968311]]


ompute the mean and standard deviation 

In [ ]:
scaler = preprocessing.StandardScaler().fit(X)

In [ ]:
print(scaler.transform(X))

[[ 0.         -0.70710678 -1.38873015  0.52489066  0.59299945 -1.35873244]
 [ 0.         -0.70710678  0.46291005  0.87481777  0.81537425  1.01904933]
 [ 0.          1.41421356  0.9258201  -1.39970842 -1.4083737   0.33968311]]


caling features to lie between a given minimum and maximum value, often between zero and one<br>
r so that the maximum absolute value of each feature is scaled to unit size

In [ ]:
min_max_scaler = preprocessing.MinMaxScaler()
X_minmax = min_max_scaler.fit_transform(X)
print(X_minmax)

[[0.         0.         0.         0.84615385 0.9        0.        ]
 [0.         0.         0.8        1.         1.         1.        ]
 [0.         1.         1.         0.         0.         0.71428571]]


In [ ]:
max_abs_scaler = preprocessing.MaxAbsScaler()
X_max = max_abs_scaler.fit_transform(X)
print(X_max)

[[0.         0.         0.33333333 0.86666667 0.9        0.06666667]
 [0.         0.         0.86666667 1.         1.         1.        ]
 [0.         1.         1.         0.13333333 0.         0.73333333]]


<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=486c3042-68b8-438c-a156-48d94106b4cb' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>